# (The MIT License)
#
# SPDX-FileCopyrightText: Copyright (c) 2023-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.23.1
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |
  pdd -f /dev/null
  bundle install --no-color
release:
  pre: false
  script: |-
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" jekyll-chatgpt-translate.gemspec
    sed -i "s/0\.0\.0/${tag}/g" lib/jekyll-chatgpt-translate/version.rb
    git add jekyll-chatgpt-translate.gemspec
    git add lib/jekyll-chatgpt-translate/version.rb
    git commit -m "version set to ${tag}"
    gem build jekyll-chatgpt-translate.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake
